id: get_sketch_url
description: Piassa WebSocket Link
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /api/ws
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 128MB
    call: GetSketchSocket
